### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by akiym**

### CODE REVIEW

**Comment by vti** [comment]
This `DB` file is auto generated by `util/generate`. Probably should just rerun it. Also if removing commas, we have to make sure that the versions are correctly parsed by `CPAN::Audit::Version`.

**Comment by akiym** [comment]
@vti Could you tell me how to generate DB file using util/generate? It seems require some YAML file.

**Comment by vti** [comment]
@akiym yeah, it needs some dev dependencies, which are not included in cpanfile:
- YAML::Tiny
- CPAN::DistnameInfo
- HTTP::Tiny

**Comment by akiym** [comment]
Uh I have to fix https://github.com/vti/cpan-security-advisory before generate DB.

**Comment by vti** [comment]
But wait, the version specification format should stay according to https://metacpan.org/pod/CPAN::Meta::Spec#Version-Ranges

**Comment by akiym** [comment]
I fixed typo and version format at https://github.com/vti/cpan-security-advisory/pull/1. I will regenerate the DB file with another PR.

**Pull request closed without merging**
