### PR TITLE
Support loading dist info from cpanfile.snapshot

### PR DESCRIPTION
**Pull request by akiym**

### CODE REVIEW

**Comment by vti** [comment]
Can't we look at `cpanfile.snapshot` instead of parsing `.meta` of all dependencies?

**Comment by akiym** [comment]
Sounds good, let me try.

**Comment by akiym** [comment]
I tried to get some information from cpanfile.snapshot, but it can't determine actual version of provided modules.
For example DBI has several different module versions in provides.

```
DISTRIBUTIONS
  DBI-1.641
    pathname: T/TI/TIMB/DBI-1.641.tar.gz
    provides:
      Bundle::DBI 12.008696
      DBD::DBM 0.08
...
      DBI 1.641
...
```

I suppose parsing .meta is not too bad idea, how is this? @vti

**Comment by vti** [comment]
CPAN-Audit tracks distribution version, not specific modules, so in this case DBI-1.641 should be taken and parsed with CPAN::DistnameInfo.

**Comment by akiym** [comment]
I got it. Thank you for the advice. I'm going to use CPAN::DistnameInfo.
By the way, I also found the module which have different version from version part in the distribution name. Basically CPAN::DistnameInfo should be okay.
https://explorer.metacpan.org/?url=/module/Net::SynchroEdit::Service

**Comment by vti** [comment]
Yes, there are some modules with different version numbers, but generally it's an error and we cannot actually install modules from CPAN, we always install a distribution. That is why I decided to go with the dist version.

**Comment by akiym** [comment]
Rebased.

**Pull request merged**
